"use strict";
// One IPC table -> the preload bridge, its .d.ts, and the main-process handler
// registration check. The three used to be hand-synced copies.
//
//   defineIpc({
//     global: "zevet",                       // window.zevet
//     dtsHeader: 'import type { X } from "./x";',   // optional, verbatim at the top of the .d.ts
//     calls: {                               // renderer -> main, ipcRenderer.invoke
//       test: { channel: "zevet:test", params: [["hub", "string"], ["token", "string"]],
//               pack: "object", returns: "Promise<{ ok: boolean }>", doc: "…" },
//     },
//     events: {                              // main -> renderer push; returns an unsubscribe
//       onUpdate: { channel: "app:update", payload: "UpdateStatus", doc: "…" },
//     },
//   })
//
// pack: "spread" (default) sends the params as separate invoke args;
//       "object" sends one `{ a, b }` object keyed by the param names.
// Type strings are the author's, verbatim: the table is the only place they live.

const IDENT = /^[A-Za-z_$][\w$]*$/;
const CHANNEL = /^[A-Za-z0-9:_./-]+$/;

function defineIpc(spec) {
  if (!spec || !IDENT.test(spec.global || "")) throw new Error("defineIpc: `global` must be an identifier");
  const calls = spec.calls || {};
  const events = spec.events || {};
  const channels = new Map();
  const claim = (name, channel) => {
    if (!IDENT.test(name)) throw new Error(`defineIpc: "${name}" is not an identifier`);
    if (typeof channel !== "string" || !CHANNEL.test(channel)) throw new Error(`defineIpc: ${name}: bad channel ${JSON.stringify(channel)}`);
    if (channels.has(channel)) throw new Error(`defineIpc: channel "${channel}" is used by both ${channels.get(channel)} and ${name}`);
    channels.set(channel, name);
  };
  for (const [name, c] of Object.entries(calls)) {
    claim(name, c.channel);
    if (typeof c.returns !== "string") throw new Error(`defineIpc: ${name}: \`returns\` type is required`);
    if (c.pack !== undefined && c.pack !== "spread" && c.pack !== "object") throw new Error(`defineIpc: ${name}: pack must be "spread" or "object"`);
    for (const p of c.params || []) {
      if (!Array.isArray(p) || !IDENT.test(p[0]) || typeof p[1] !== "string") throw new Error(`defineIpc: ${name}: params are [name, type] pairs`);
    }
  }
  for (const [name, e] of Object.entries(events)) {
    claim(name, e.channel);
    if (typeof e.payload !== "string") throw new Error(`defineIpc: ${name}: \`payload\` type is required`);
  }
  if (Object.keys(calls).some((n) => n in events)) throw new Error("defineIpc: a name is both a call and an event");
  return Object.freeze({ global: spec.global, dtsHeader: spec.dtsHeader || "", calls, events });
}

const doc = (text, indent) => (text ? `${indent}/** ${String(text).replace(/\*\//g, "* /")} */\n` : "");

/** Source of a CommonJS preload script exposing `window.<global>`. */
function generatePreload(table) {
  const lines = [];
  for (const [name, c] of Object.entries(table.calls)) {
    const names = (c.params || []).map((p) => p[0]);
    const args = c.pack === "object" && names.length ? `{ ${names.join(", ")} }` : names.join(", ");
    lines.push(`${doc(c.doc, "  ")}  ${name}: (${names.join(", ")}) => ipcRenderer.invoke(${JSON.stringify(c.channel)}${args ? `, ${args}` : ""}),`);
  }
  for (const [name, e] of Object.entries(table.events)) {
    lines.push(`${doc(e.doc, "  ")}  ${name}: (fn) => subscribe(${JSON.stringify(e.channel)}, fn),`);
  }
  return `// GENERATED by @masora/desktop-kit from the IPC table. Do not edit; change the table.
"use strict";
const { contextBridge, ipcRenderer } = require("electron");

/** Subscribe to a main-process push; returns the way to stop. */
function subscribe(channel, fn) {
  const handler = (_e, payload) => fn(payload);
  ipcRenderer.on(channel, handler);
  return () => ipcRenderer.removeListener(channel, handler);
}

contextBridge.exposeInMainWorld(${JSON.stringify(table.global)}, {
${lines.join("\n")}
});
`;
}

/** Source of the .d.ts for `window.<global>`. */
function generateDts(table) {
  const type = `${table.global[0].toUpperCase()}${table.global.slice(1)}Bridge`;
  const lines = [];
  for (const [name, c] of Object.entries(table.calls)) {
    const params = (c.params || []).map(([n, t]) => `${n}: ${t}`).join(", ");
    lines.push(`${doc(c.doc, "  ")}  ${name}(${params}): ${c.returns};`);
  }
  for (const [name, e] of Object.entries(table.events)) {
    lines.push(`${doc(e.doc, "  ")}  ${name}(fn: (payload: ${e.payload}) => void): () => void;`);
  }
  return `// GENERATED by @masora/desktop-kit from the IPC table. Do not edit; change the table.
${table.dtsHeader ? `${table.dtsHeader}\n` : ""}
export interface ${type} {
${lines.join("\n")}
}

declare global {
  interface Window {
    ${table.global}: ${type};
  }
}
`;
}

/** Register `handlers` (name -> fn(event, ...args)) on ipcMain for every call in
 *  the table. Throws on a call with no handler or a handler with no call, so the
 *  main side cannot drift from the table. */
function registerIpc(ipcMain, table, handlers) {
  const missing = Object.keys(table.calls).filter((n) => typeof handlers[n] !== "function");
  const extra = Object.keys(handlers).filter((n) => !(n in table.calls));
  if (missing.length || extra.length) {
    throw new Error(`registerIpc: table/handler drift — no handler for [${missing}], no call for [${extra}]`);
  }
  for (const [name, c] of Object.entries(table.calls)) ipcMain.handle(c.channel, handlers[name]);
}

module.exports = { defineIpc, generatePreload, generateDts, registerIpc };
